apiVersion: v1
kind: Template
labels:
  app: esearchexporter
  template: esearchexporter-buildconfig
metadata:
  annotations:
    description: ElasticSearch exporter - BuildConfig
      see https://github.com/Worteks/docker-esearchexporter
    iconClass: icon-openshift
    openshift.io/display-name: ElasticSearch Exporter
    tags: esearchexporter
  name: esearchexporter-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds ElasticSearch Exporter images
    labels:
      name: esearchexporter-${FRONTNAME}-${ELASTICSEARCH_EXPORTER_REPOSITORY_REF}
    name: esearchexporter-${FRONTNAME}-${ELASTICSEARCH_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${ELASTICSEARCH_EXPORTER_REPOSITORY_URL}
        ref: "${ELASTICSEARCH_EXPORTER_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: esearchexporter-${FRONTNAME}:${ELASTICSEARCH_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: ELASTICSEARCH_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: ELASTICSEARCH_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your elasticsearch exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-esearchexporter.git
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
