apiVersion: v1
kind: Template
labels:
  app: esearchexporter
  template: esearchexporter-imagestream
metadata:
  annotations:
    description: ElasticSearch exporter - ImageStream
      see https://github.com/Worteks/docker-esearchexporter
    iconClass: icon-openshift
    openshift.io/display-name: ElasticSearch Exporter
    tags: esearchexporter
  name: esearchexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in ElasticSearch Exporter image
    name: esearchexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
